### ISSUE TITLE
运行时出现异常

### ISSUE THREAD

**Issue by JackShao** [WildDogTeam/video-demo-android#1]
在导入Android Studio后，在调试状态下运行，出现异常：
08-24 13:32:55.381 17840-17840/com.wilddog.demo E/CrashlyticsCore: Failed to execute task.
                                                                   java.util.concurrent.TimeoutException
                                                                       at java.util.concurrent.FutureTask.get(FutureTask.java:177)
                                                                       at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
                                                                       at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:285)
                                                                       at com.crashlytics.android.core.CrashlyticsController$5.onUncaughtException(CrashlyticsController.java:269)
                                                                       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:30)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
08-24 13:32:55.382 17840-17840/com.wilddog.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.wilddog.demo, PID: 17840
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wilddog.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wilddog.demo-1/lib/arm, /data/app/com.wilddog.demo-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libtusdk-library.so"
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                      at org.lasque.tusdk.core.utils.NativeLibraryHelper.loadLibrary(Unknown Source)
                                                                      at org.lasque.tusdk.core.secret.SdkValid.<clinit>(Unknown Source)
                                                                      at org.lasque.tusdk.core.TuSdk.<init>(Unknown Source)
                                                                      at org.lasque.tusdk.core.TuSdk.init(Unknown Source)
                                                                      at org.lasque.tusdk.core.TuSdk.init(Unknown Source)
                                                                      at com.wilddog.demo.ConversationApplication.onCreate(ConversationApplication.java:41)
                                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4782)
                                                                      at android.app.ActivityThread.access$1700(ActivityThread.java:153)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5544)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
08-24 13:32:55.383 17840-17840/com.wilddog.demo E/MQSEventManagerDelegate: failed to get MQSService.

**Comment by laufly** [comment]
这个应该是由于没有上传tu sdk的jni导致tusdk初始化提示找不到so库,已经加入,请重新获取代码 我们只提供了sdk的集成代码.并未将key公布出来,需要集成的请到tusdk官网申请key,然后创建自己的应用参考TuSDK官方文档和我们的代码集成,如果需要体验涂图美颜的效果,可以下载我们的应用(http://fir.im/conversationDemo)体验
